# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-28 09:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialtest',
            name='date_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
            preserve_default=False,
        ),
    ]
